pipeline {
    agent any
    tools {
        maven 'Maven 3.8.5'
        jdk 'jdk-17'
    }
    environment {
        GIT_CREDENTIALS = credentials('b57a400d-f957-45ba-89f7-f2ac535737e1')
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    git url: 'https://github.com/vadym-udaltsov/test-automation-framework.git',
                        credentialsId: 'b57a400d-f957-45ba-89f7-f2ac535737e1'
                }
            }
        }
        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }
        stage('Allure Report') {
            steps {
                sh 'mvn allure:report'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'target/allure-results/**', allowEmptyArchive: true
        }
    }
}
