pipeline {
    agent any
    tools {
        maven 'Maven 3.8.5'
        jdk 'jdk-17'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/vadym-udaltsov/test-automation-framework.git'
            }
        }
        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }
        stage('Allure Report') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: 'jdk-17',
                    results: [[path: 'target/allure-results']]
                ])
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'target/allure-results/**', allowEmptyArchive: true
        }
    }
}
